# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcbff57991df6204211a4110001218ab444c77b8743b7367a3c098d4aed95292c9aaf069b064d77f11fcd61e8f6be65c2e6a9d9e6dbd3465ce8be6e96fb56195

test:
  secret_key_base: c25f81e9c02a9961e6d976309e58166dd43e1c8892088badc43d7baa5a5aa653aead9c4739a9e713eee4b5a94978081cbdd166248ac64071844777bc9ff9af72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
